name: 'ReleaseTag-Action'
description: 'Publish and update release notes to ReleaseTag'
inputs:
  version:
    description: 'Release Version'
    required: true
  previous-tag:
    description: 'Tag of last release'
    required: false
  previous-tag-matching:
    description: 'Pattern of last release tag'
    required: false
runs:
  using: "composite"
  steps:    
    - run: releasetag.sh -v ${{ inputs.version }} -p ${{ inputs.previous-tag }} -m ${{ inputs.previous-tag-matching }}
      shell: bash
